FROM nginx
COPY html /usr/share/nginx/html

#RUN apt-get update && apt-get install -y wget xz-utils git
#
#RUN mkdir $HOME/Downloads
#RUN wget -O $HOME/Downloads/node-install.tar.xz https://nodejs.org/dist/v6.2.1/node-v6.2.1-linux-x64.tar.xz
#
#RUN mkdir /opt/node
#RUN tar xvfJ $HOME/Downloads/node-install.tar.xz -C /opt/node --strip-components=1
#ENV PATH "$PATH:/opt/node/bin"
#
#RUN npm install -g bower
#RUN echo '{ "allow_root": true }' > /root/.bowerrc
#
#RUN cd /usr/share/nginx/html && bower install
